version: '3'
services:
  mysql:
    image: mysql:5.7.9
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - mysql-compose-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    networks:
      - mysql-compose-network

volumes:
  mysqldata: null

networks:
  mysql-compose-network:
    driver: bridge